---
stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"
  GIT_STRATEGY: clone

cache:
    paths:
    - .pip/
    - .env/

test:
  stage: test
  only:
    - develop
  tags:
    - test
  script:
    - pip3 install virtualenv
    - python3 -m virtualenv .env
    - source .env/bin/activate
    - pip install -r requirements.txt
    - ansible-galaxy install -r requirements.yml # -f
    - python -V
    - pip -V
    - ansible --version
    - ansible-playbook playbook.yml -i hosts.ini
...
