---
# ckaserer.haproxy
  haproxy_frontend:
    - name: oc-machineset
      bind:
        - listen: ':22623'
      mode: tcp
      option:
        - dontlog-normal
      default_backend: oc-machineset-backend 
    - name: oc-api
      bind:
        - listen: ':6443'
      mode: tcp
      option:
        - dontlog-normal
      default_backend: oc-api-backend
    - name: oc-worker-http
      bind:
        - listen: ':80'
      mode: tcp
      option:
        - dontlog-normal
      default_backend: oc-worker-http-backend
    - name: oc-worker-https
      bind:
        - listen: ':443'
      mode: tcp
      option:
        - dontlog-normal
      default_backend: oc-worker-https-backend

  haproxy_backend:
    - name: oc-api-backend
      mode: tcp
      option:
        - dontlog-normal
      balance: source
      server:
        - name: bootstrap
          listen: '10.20.24.9:6443'
          param:
            - check
        - name: master-0
          listen: '10.20.24.10:6443'
          param:
            - check
        - name: master-1
          listen: '10.20.24.11:6443'
          param:
            - check
        - name: master-2
          listen: '10.20.24.12:6443'
          param:
            - check

    - name: oc-machineset-backend
      mode: tcp
      option:
        - dontlog-normal
      balance: source
      server:
        - name: bootstrap
          listen: '10.20.24.9:22623'
          param:
            - check
        - name: master-0
          listen: '10.20.24.10:22623'
          param:
            - check
        - name: master-1
          listen: '10.20.24.11:22623'
          param:
            - check
        - name: master-2
          listen: '10.20.24.12:22623'
          param:
            - check

    - name: oc-worker-http-backend
      mode: tcp
      option:
        - dontlog-normal
      balance: source
      server:
        - name: oc-worker-http-0
          listen: '10.20.24.20:80'
          param:
            - check
        - name: oc-worker-http-1
          listen: '10.20.24.21:80'
          param:
            - check
        - name: oc-worker-http-2
          listen: '10.20.24.22:80'
          param:
            - check
        - name: oc-worker-http-3
          listen: '10.20.24.23:80'
          param:
            - check
        - name: oc-worker-http-4
          listen: '10.20.24.24:80'
          param:
            - check
        - name: oc-worker-http-5
          listen: '10.20.24.25:80'
          param:
            - check
        - name: oc-worker-http-6
          listen: '10.20.24.26:80'
          param:
            - check
        - name: oc-worker-http-7
          listen: '10.20.24.27:80'
          param:
            - check
        - name: oc-worker-http-8
          listen: '10.20.24.28:80'
          param:
            - check
        - name: oc-worker-http-9
          listen: '10.20.24.29:80'
          param:
            - check

    - name: oc-worker-https-backend
      mode: tcp
      option:
        - dontlog-normal
      balance: source
      server:
        - name: oc-worker-https-0
          listen: '10.20.24.20:443'
          param:
            - check
        - name: oc-worker-https-1
          listen: '10.20.24.21:443'
          param:
            - check
        - name: oc-worker-https-2
          listen: '10.20.24.22:443'
          param:
            - check
        - name: oc-worker-https-3
          listen: '10.20.24.23:443'
          param:
            - check
        - name: oc-worker-https-4
          listen: '10.20.24.24:443'
          param:
            - check
        - name: oc-worker-https-5
          listen: '10.20.24.25:443'
          param:
            - check
        - name: oc-worker-https-6
          listen: '10.20.24.26:443'
          param:
            - check
        - name: oc-worker-https-7
          listen: '10.20.24.27:443'
          param:
            - check
        - name: oc-worker-https-8
          listen: '10.20.24.28:443'
          param:
            - check
        - name: oc-worker-https-9
          listen: '10.20.24.29:443'
          param:
            - check

#bertvv.bind config
  bind_allow_query:
    - any
  bind_listen_ipv4:
    - any
  bind_listen_ipv6:
    - any
  bind_forwarders:
    - '8.8.8.8'
    - '8.8.4.4'
  bind_recursion: true
  bind_query_log: 'data/query.log'
  bind_check_names: 'master ignore'
  bind_zone_master_server_ip: "10.20.26.12"
  bind_zone_minimum_ttl: "2D"
  bind_zone_ttl: "2W"
  bind_zone_time_to_refresh: "2D"
  bind_zone_time_to_retry: "2H"
  bind_zone_time_to_expire: "2W"
  bind_zones:
    - name: 'gp.local'
      networks:
        - '10.20.26'
      primaries:
        - '10.20.26.12'
      hostmaster_email: "noreply@no.reply"
      hosts:
        - name: "gp-bastion"
          ip: "10.20.26.11"
        - name: "gp-service"
          ip: "10.20.26.12"
    - name: 'ocp.gp.local'
      networks:
        - '10.20.24'
      primaries:
        - '10.20.26.12'
      hostmaster_email: "noreply@no.reply"
      hosts:
        - name: "gp-service"
          ip: "10.20.26.12"
          aliases:
            - "*.apps"
            - api
            - api-int
        - name: "bootstrap"
          ip: "10.20.24.9"
        - name: "master0"
          ip: "10.20.24.10"
        - name: "master1"
          ip: "10.20.24.11"
        - name: "master2"
          ip: "10.20.24.12"
        - name: "worker0"
          ip: "10.20.24.20"
        - name: "worker1"
          ip: "10.20.24.21"
        - name: "worker2"
          ip: "10.20.24.22" 
        - name: "worker3"
          ip: "10.20.24.23"
        - name: "worker4"
          ip: "10.20.24.24"
        - name: "worker5"
          ip: "10.20.24.25"
        - name: "worker6"
          ip: "10.20.24.26"
        - name: "worker7"
          ip: "10.20.24.27"
        - name: "worker8"
          ip: "10.20.24.28"
        - name: "worker9"
          ip: "10.20.24.29"

# ckaserer.tftp

# ckaserer.pxeserver
  pxeserver_ip: 10.20.26.12
  pxeserver_images:
    - name: centos7_x86_64
      default: true
      kernel_url: http://mirror.centos.org/centos/7/os/x86_64/images/pxeboot/vmlinuz
      initrd_url: http://mirror.centos.org/centos/7/os/x86_64/images/pxeboot/initrd.img
      label: CentOS 7 x86_64

# ckaserer.dhcp
  dhcp_global_next_server: "10.20.26.12"
  dhcp_global_ntp_servers: 
    - 91.206.8.36     # 0.at.pool.ntp.org
    - 80.92.126.65    # 0.at.pool.ntp.org
    - 194.112.182.172 # 1.at.pool.ntp.org
    - 86.59.80.170    # 1.at.pool.ntp.org
  dhcp_global_authoritative: authoritative
  dhcp_global_default_lease_time: 28800   # 8hrs
  dhcp_global_max_lease_time: 43200       # 12 hrs
  dhcp_global_routers: "10.20.26.12"
  dhcp_global_domain_name: gp.local
  dhcp_global_domain_name_servers:
    - 8.8.8.8
    - 8.8.4.4
  dhcp_interface: eth0
  dhcp_subnets:
    - ip: 10.20.24.0
      netmask: 255.255.252.0
      routers: "10.20.26.254"
      domain_name_servers:
        - "10.20.26.12"
      range_begin: 10.20.24.100
      range_end: 10.20.24.250
  dhcp_hosts:
    - name: gp-bastion
      mac: '00:15:5d:43:79:2f'
      ip: "10.20.26.11"
    - name: "bootstrap"
      mac: '00:11:22:33:44:01'
      ip: "10.20.24.9"
    - name: "master0"
      mac: '00:11:22:33:44:02'
      ip: "10.20.24.10"
    - name: "master1"
      mac: '00:11:22:33:44:03'
      ip: "10.20.24.11"
    - name: "master2"
      mac: '00:11:22:33:44:04'
      ip: "10.20.24.12"
    - name: "worker0"
      mac: '00:11:22:33:44:05'
      ip: "10.20.24.20"
    - name: "worker1"
      mac: '00:11:22:33:44:06'
      ip: "10.20.24.21"
    - name: "worker2"
      mac: '00:11:22:33:44:07'
      ip: "10.20.24.22" 
    - name: "worker3"
      mac: '00:11:22:33:44:08'
      ip: "10.20.24.23"
    - name: "worker4"
      mac: '00:11:22:33:44:09'
      ip: "10.20.24.24"
    - name: "worker5"
      mac: '00:11:22:33:44:10'
      ip: "10.20.24.25"
    - name: "worker6"
      mac: '00:11:22:33:44:11'
      ip: "10.20.24.26"
    - name: "worker7"
      mac: '00:11:22:33:44:12'
      ip: "10.20.24.27"
    - name: "worker8"
      mac: '00:11:22:33:44:13'
      ip: "10.20.24.28"
    - name: "worker9"
      mac: '00:11:22:33:44:14'
      ip: "10.20.24.29"
  dhcp6_enable: false
...