---
# ckaserer.haproxy
  haproxy_frontend:
    - name: oc-machineset
      bind:
        - listen: ':22623'
      mode: tcp
      option:
        - dontlog-normal
      default_backend: oc-machineset-backend 
    - name: oc-api
      bind:
        - listen: ':6443'
      mode: tcp
      option:
        - dontlog-normal
      default_backend: oc-api-backend
    - name: oc-worker-http
      bind:
        - listen: ':80'
      mode: tcp
      option:
        - dontlog-normal
      default_backend: oc-worker-http-backend
    - name: oc-worker-https
      bind:
        - listen: ':443'
      mode: tcp
      option:
        - dontlog-normal
      default_backend: oc-worker-https-backend

  haproxy_backend:
    - name: oc-api-backend
      mode: tcp
      option:
        - dontlog-normal
      balance: source
      server:
        - name: bootstrap
          listen: '10.20.24.9:6443'
          param:
            - check
        - name: master-0
          listen: '10.20.24.10:6443'
          param:
            - check
        - name: master-1
          listen: '10.20.24.11:6443'
          param:
            - check
        - name: master-2
          listen: '10.20.24.12:6443'
          param:
            - check

    - name: oc-machineset-backend
      mode: tcp
      option:
        - dontlog-normal
      balance: source
      server:
        - name: bootstrap
          listen: '10.20.24.9:22623'
          param:
            - check
        - name: master-0
          listen: '10.20.24.10:22623'
          param:
            - check
        - name: master-1
          listen: '10.20.24.11:22623'
          param:
            - check
        - name: master-2
          listen: '10.20.24.12:22623'
          param:
            - check

    - name: oc-worker-http-backend
      mode: tcp
      option:
        - dontlog-normal
      balance: source
      server:
        - name: oc-worker-http-0
          listen: '10.20.24.20:80'
          param:
            - check
        - name: oc-worker-http-1
          listen: '10.20.24.21:80'
          param:
            - check
        - name: oc-worker-http-2
          listen: '10.20.24.22:80'
          param:
            - check
        - name: oc-worker-http-3
          listen: '10.20.24.23:80'
          param:
            - check
        - name: oc-worker-http-4
          listen: '10.20.24.24:80'
          param:
            - check
        - name: oc-worker-http-5
          listen: '10.20.24.25:80'
          param:
            - check
        - name: oc-worker-http-6
          listen: '10.20.24.26:80'
          param:
            - check
        - name: oc-worker-http-7
          listen: '10.20.24.27:80'
          param:
            - check
        - name: oc-worker-http-8
          listen: '10.20.24.28:80'
          param:
            - check
        - name: oc-worker-http-9
          listen: '10.20.24.29:80'
          param:
            - check

    - name: oc-worker-https-backend
      mode: tcp
      option:
        - dontlog-normal
      balance: source
      server:
        - name: oc-worker-https-0
          listen: '10.20.24.20:443'
          param:
            - check
        - name: oc-worker-https-1
          listen: '10.20.24.21:443'
          param:
            - check
        - name: oc-worker-https-2
          listen: '10.20.24.22:443'
          param:
            - check
        - name: oc-worker-https-3
          listen: '10.20.24.23:443'
          param:
            - check
        - name: oc-worker-https-4
          listen: '10.20.24.24:443'
          param:
            - check
        - name: oc-worker-https-5
          listen: '10.20.24.25:443'
          param:
            - check
        - name: oc-worker-https-6
          listen: '10.20.24.26:443'
          param:
            - check
        - name: oc-worker-https-7
          listen: '10.20.24.27:443'
          param:
            - check
        - name: oc-worker-https-8
          listen: '10.20.24.28:443'
          param:
            - check
        - name: oc-worker-https-9
          listen: '10.20.24.29:443'
          param:
            - check
...