---
network_ip: "192.168.0"                   # easy to change network ip if it is a class c network
netmask: '255.255.255.0'                  # class c network netmask
mac_prefix: '00:11:22:33:44'
...
