- hosts: gp_service
  become: true
  pre_tasks:
  
    - name: Update apt cache
      apt:
        update_cache: yes

  tasks:

    - name: Install required packages
      apt:
        name: 
          - git
          - python3
          - python3-pip

    - name: Include ckaserer.haproxy
      include_role:
        name: ckaserer.haproxy
    