---
- name: Service Playbook
  hosts: all
  become: true

  vars_files:
    - default.config.yml
  
  pre_tasks:
  
    - name: change hostname to service0
      hostname:
        name: "service0"

    - name: Update apt cache
      apt:
        update_cache: true

    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/defaults/*.yml"
      tags: ['always']

  tasks:

    - name: Install required packages
      apt:
        name: 
          - git
          - python3
          - python3-pip
          - python3-apt
          - net-tools

    - name: Include ckaserer.bind
      include_role:
        name: ckaserer.bind
      tags:
        - bind

    - name: Include ckaserer.dhcp
      include_role:
        name: ckaserer.dhcp
      tags:
        - dhcp

    - name: Include ckaserer.haproxy
      include_role:
        name: ckaserer.haproxy
      tags:
        - haproxy

    - name: Include ckaserer.nginx
      include_role:
        name: ckaserer.nginx
      tags:
        - nginx

    - name: Include ckaserer.tftp
      include_role:
        name: ckaserer.tftp
      tags:
        - pxe

    # - name: Include ckaserer.pxeserver
    #   include_role:
    #     name: ckaserer.pxeserver
    #   tags:
    #     - pxe


...
