- hosts: gp_service
  become: true

  vars_files:
    - default.config.yml
  
  pre_tasks:
  
    - name: Update apt cache
      apt:
        update_cache: yes

    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:

    - name: Install required packages
      apt:
        name: 
          - git
          - python3
          - python3-pip

    - name: Include ckaserer.haproxy
      include_role:
        name: ckaserer.haproxy
        
    - name: Include bertvv.bind
      include_role:
        name: bertvv.bind

    - name: Include ckaserer.dhcp
      include_role:
        name: ckaserer.dhcp
    