---
name: Develop Branch

'on':
  push:
    branches:
      - develop
    tags-ignore:
      - '**'
  schedule:
    - cron: '30 8 * * 3'

jobs:

  linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          FILTER_REGEX_EXCLUDE: '.*.md'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sandbox:
    name: Sandbox Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install pip Dependencies
        run: pip3 install -r requirements.txt

      - name: Install ansible galaxy Dependencies
        run: ansible-galaxy install -r requirements.yml
      
      - name: Run ansible playbook
        run: ansible-playbook --connection=local --inventory 127.0.0.1, playbook.yml

  # deploy:

  # test:

  # merge:
  #   name: Merge to main
  #   runs-on: ubuntu-latest
  #     if: github.ref == 'refs/heads/develop'
  #   needs:
  #     - linter
  #     - molecule
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2

  #     - name: Create Pull Request
  #       uses: peter-evans/create-pull-request@v3
  #       with:
  #         branch: main

  # notify:
  #   name: "Notify #test Channel"
  #   runs-on: ubuntu-latest
  #   if: ${{ failure() }}
  #   needs:
  #     - sandbox
  #     - linter
  #     - merge2develop
  #   steps:
  #     - name: "Notify Slack channel #fail"
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  #         SLACK_ICON: https://github.com/ckaserer/logos/raw/master/ansible.png
  #         SLACK_USERNAME: ${{ github.repository }}
  #         SLACK_COLOR: '#ff0033'
  #         SLACK_FOOTER: ''

...
